use_frameworks!

platform :ios, '8.0'

target 'XKLocationManager_Example' do
  pod 'XKLocationManager', :path => '../'

  target 'XKLocationManager_Tests' do
    inherit! :search_paths

    
  end
end
